### ISSUE TITLE
Unable to load c9

### ISSUE THREAD

**Issue by knkrth** [HuJK/Cloud9-hub#1]
I have installed as per the steps provided in the [README.md](https://github.com/HuJK/Cloud9-hub/blob/master/README.md) After `nginx -s reload` I visit the `localhost` on my browser, It only displays the "Welcome to nginx!" page.

Can you provide any steps on how to get into c9 workspace page?

**Comment by HuJK** [comment]
Sorry I forgot I did some workaround to make it work, but not record in "readme.md".
Now I finished "Postinstall" part in Readme. Please follow it.

and please do
```
chmod 755 /etc/c9/sdk
chmod 755 /etc/c9/.c9
```

If other problems occurs, welcome to ask for help.

**Comment by HuJK** [comment]
I'm use domain based virtual host. And I upload my config directly.
Now I update it to port based virtual host version

So the step should become more simple.

Please install again from "Install" step.

**Comment by knkrth** [comment]
Ok, thanks. Is there any demo link available?

**Comment by knkrth** [comment]
Are you planning to dockerize the c9 ide for better isolation?

**Comment by HuJK** [comment]
I wrote a install script here:

```sh -c "$(wget -O- https://raw.githubusercontent.com/HuJK/Cloud9-hub/master/install.sh)"```

And have been tested on a new ubuntu 18.04 on amazon ec2.

Demo page:
https://3.91.27.2:8443/

Demo account:

user|passwd
------|---------
demo01|demo)!
demo02|demo)@
demo03|demo)#

**Comment by HuJK** [comment]
About dockerize ... I think not recently.

This is just a nginx config with lua block, a very simple login page for multi-user on a server. 
When user connect in, it will check instance exist or not, proxy_pass to it or spawn a new one.

Dockerize it...... theoretically possible, but not now.

Or you can fork my project and dockerize it?

**Comment by knkrth** [comment]
Dockerize this application maybe. But `--collab` option is not available.

**Comment by HuJK** [comment]
Okey, now I add "--collab" parameter in the spawn command

https://github.com/HuJK/Cloud9-hub/blob/ba3048e2b559fa9f79cffee99225a63430a76d1a/c9io#L67

**Comment by knkrth** [comment]
How to add other users to the workspace? ie. If I want to add `demo01` user to the `demo02` users workspace. 
![image](https://user-images.githubusercontent.com/12738581/64937616-7c9f4a80-d878-11e9-8c27-68e37656f7f2.png)

**Comment by HuJK** [comment]
Sorry I don't know ether. 

It seems still a open issue in original cloud9
https://github.com/c9/core/issues/241

The only thing I do is ```su``` to that user, run this command to spawn server
```node /etc/c9/sdk/server.js --collab -p $sock_path -a $server_auth -w $HOME```
and proxy_pass to $sock_path.

You can login with same account in different place. Group Chat and other collab feature are work. But all user's username is "You".

**Comment by knkrth** [comment]
Oh ok, If I find any solution I let you know.

**Comment by HuJK** [comment]
Thanks a lot. 
Let's back each other up!

**Comment by knkrth** [comment]
If you are good at JavaScript you can update this code https://github.com/farukcank/cloud9wsman/tree/develop

**Comment by knkrth** [comment]
Here is the demo link for the [cloud9wsman](https://github.com/farukcank/cloud9wsman/tree/develop) http://35.232.171.201:8080 try `admin:admin` for full access & `demo:demo` for user experience. 

There are miner changes need to be done on the `fcank/cloud9:v3` image in order to make it work.

It runs a older version of docker I tried running it on newer version of c9 v3 but I got `event error` 

If you want I can send you the docker file of the latest c9 v3 to test it with the [cloud9wsman](https://github.com/farukcank/cloud9wsman/tree/develop) 

It runs on ubuntu 14 without any errors, On ubuntu 18 you will get a error related to redis db.

**Comment by knkrth** [comment]
Demo url is not working https://3.91.27.2:8443/ remove it from readme.

**Comment by knkrth** [comment]
Do u hav any plan to work on? https://github.com/farukcank/cloud9wsman/tree/develop

**Comment by HuJK** [comment]
Currently I don't have plan to work on farukcank/cloud9wsman now. 

But I think after I finish all of this, I can pack it into docker, and than switch spawn command into
```lua
os.execute("docker run --name=" .. username .. "-" .. md5(serversalt .. userpass) .. " 
                       -v /etc/c9/sock:/etc/c9/sock 
                       whojk/img_name 
                       node /etc/c9/sdk/server.js --collab 
                                                  -p " .. server_sock_path .. " 
                                                  -a " .. server_auth .. " 
                                                  -w /root
          ")
```
to dockerize it

But every user still can only have one instance. Because I use username+password to identify which instance should I proxy_pass to.

**Comment by knkrth** [comment]
Cool :)

**Comment by knkrth** [comment]
Take a look at this https://github.com/YusukeIwaki/cloud-pine

**Comment by HuJK** [comment]
Oh, thanks, I saw it.
The problem is it use hostname to proxy_pass to different backend. But it need wildcard domain, and I want to aviod it. Because usually it's not free, you have to pay to get a domain with wildcard domain function.

Even though I bought one, the setup of dns record and ddns script is not easy, and different company has different setup step. It is not possible to write a single script to setup whole things.

I want to keep the installation process simple, my solution is simply use username to proxy_pass to different backend, so each user can only have one backend only.

Do you have better idea to solve this?

**Comment by HuJK** [comment]
> Demo url is not working https://3.91.27.2:8443/ remove it from readme.

Sometimes I would change IP because I want to test the installation script. So I was removed the aws instance and create a new one, than run the install script.

**Comment by knkrth** [comment]
> Oh, thanks, I saw it.
> The problem is it use hostname to proxy_pass to different backend. But it need wildcard domain, and I want to aviod it. Because usually it's not free, you have to pay to get a domain with wildcard domain function.
> 
> Even though I bought one, the setup of dns record and ddns script is not easy, and different company has different setup step. It is not possible to write a single script to setup whole things.
> 
> I want to keep the installation process simple, my solution is simply use username to proxy_pass to different backend, so each user can only have one backend only.
> 
> Do you have better idea to solve this?

Can we change the https://github.com/YusukeIwaki/cloud-pine to use the default c9.io url style like https://your_ip_address/username/workspace_name by this way we don't need domain name with  wildcard.

**Comment by HuJK** [comment]
Cloud9 SDK don't have subpath option, so currently it's not possible.

https://community.c9.io/t/run-cloud9-under-subdirectory/8152/12

The only option is use subdomain. Or patch the c9 source code.

**Comment by knkrth** [comment]
I find this https://github.com/Taisun-Docker/taisun which pulls the cloud9 docker image & run it on the specified port. Collaboration option is removed, I raise an issue there.
